spring.application.name=FaunaScan


spring.datasource.url=jdbc:postgresql://localhost:5432/FaunaScanDB
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=moolasol

spring.web.error.include-stacktrace=never

debug=true

logging.level.root=INFO
logging.level.org.springframework.web=info
logging.file.name=logs/api.log